### ISSUE TITLE
Zig error: redeclaration of `log` breaking release after packaging

### ISSUE THREAD

**Issue by filipecabaco** [burrito-elixir/burrito#101]
### Host
**Host OS**: MacOS 13.4.1
**Host CPU**:  arm64 

Please run `zig version` in your Burrito project directory and write the version here: `0.10.0`

Please run `elixir -v` in your Burrito project directory and write the version here: `Elixir 1.14.4 (compiled with Erlang/OTP 25)`

------

### Target

**Host OS**: MacOS 13.4.1
**Host CPU**:  aarch64
**Host LibC and Version** (eg. gnu/musl x.y.z ...)

------
With the config
```elixir
defp releases do
    [
      desktop: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          targets: [
            desktop: [os: :darwin, cpu: :aarch64]
          ]
        ]
      ]
    ]
  end
``` 

When I run `mix release desktop`

I'm getting the following error:
```
----> PHASE: :build
--> Generating wrapper metadata file...
info: Zig is building an Elixir binary... ⚡
info: Generating and compressing release payload... 📦
info: 🔍 Files Packed: 1366
info: Archived 1366 files into payload! 📥
info: Building wrapper and embedding payload... 🌯
info: DONE 🚀
/Users/filipecabaco/workspace/example_desktop/deps/burrito/src/logger.zig:13:5: error: redeclaration of 'log'
pub fn log(comptime message: []const u8, args: anytype) void {
~~~~^~
/Users/filipecabaco/workspace/example_desktop/deps/burrito/src/logger.zig:3:1: note: other declaration here
var log = std.log;
^~~~~~~~~~~~~~~~~
error: desktop...
error: The following command exited with error code 1:
/Users/filipecabaco/.asdf/installs/zig/0.10.0/zig build-exe /Users/filipecabaco/workspace/example_desktop/deps/burrito/src/wrapper.zig -lc /Users/filipecabaco/workspace/example_desktop/deps/burrito/src/xz/xz_crc32.c /Users/filipecabaco/workspace/example_desktop/deps/burrito/src/xz/xz_dec_lzma2.c /Users/filipecabaco/workspace/example_desktop/deps/burrito/src/xz/xz_dec_stream.c --cache-dir /Users/filipecabaco/workspace/example_desktop/deps/burrito/zig-cache --global-cache-dir /Users/filipecabaco/.cache/zig --name desktop -target aarch64-macos -mcpu generic --pkg-begin build_options /Users/filipecabaco/workspace/example_desktop/deps/burrito/zig-cache/options/tg4kBJe_XTPRl84wdcNq1PJJXRu06Zj_uauSz144lrVjLsfyeUf54HELbJYwPruD --pkg-end --pkg-begin burrito_plugin /Users/filipecabaco/workspace/example_desktop/deps/burrito/_dummy_plugin.zig --pkg-end -I /Users/filipecabaco/workspace/example_desktop/deps/burrito/src/xz --enable-cache 
error: the following build command failed with exit code 1:
/Users/filipecabaco/workspace/example_desktop/deps/burrito/zig-cache/o/74ecc9694f7bfa04da1f62b82906a081/build /Users/filipecabaco/.asdf/installs/zig/0.10.0/zig /Users/filipecabaco/workspace/example_desktop/deps/burrito /Users/filipecabaco/workspace/example_desktop/deps/burrito/zig-cache /Users/filipecabaco/.cache/zig -Dtarget=aarch64-macos
--> Cleaning up...
--> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.4) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.14.4) lib/mix/tasks/release.ex:1068: Mix.Tasks.Release.run_steps/1
    (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

I thought it could be on the clean process but if I try the `no_clean: true` flag on the release command I still get the same error.

**Comment by filipecabaco** [comment]
Reverted to a previous hash that didn't include 73376ef0d76ce4842dd084bb5584c2156cca47fa and this seems to trigger this specific issue.

**Comment by doawoo** [comment]
Thanks for finding that, I'll kick a fix up in a moment so `main` can function again!

**Comment by mhanberg** [comment]
🥵

**Comment by doawoo** [comment]
see if the latest commit on `main` fixes it!

**Comment by filipecabaco** [comment]
Confirmed! working without issues! Thank you so much for the fast reply and fix 🙏

Closing this 👍
