### ISSUE TITLE
Missing handling of local unpacked `:custom_erts` setting

### ISSUE THREAD

**Issue by jozuas** [burrito-elixir/burrito#104]
When setting `:custom_erts` to a local unpacked Erlang directory, it seems that there is missing `:local_unpacked` handling.

Line 67 sets return to `{:local_unpacked, path: custom_location}`:
https://github.com/burrito-elixir/burrito/blob/5c7b29811279f3272005534a3fec29a687e9b6bf/lib/builder/target.ex#L56-L75

`do_resolve` only handles `:local`, no handling of `:local_unpacked`:
https://github.com/burrito-elixir/burrito/blob/5c7b29811279f3272005534a3fec29a687e9b6bf/lib/util/default_erts_resolver.ex#L13-L46

The runtime error:
```
--> Resolving ERTS: {:local_unpacked, [path: "/nix/store/hcl90mwii5l0mrsnrwlywh1da450ixqq-erlang-26.0.2/lib/erlang"]}
** (FunctionClauseError) no function clause matching in Burrito.Util.DefaultERTSResolver.do_resolve/1

    The following arguments were given to Burrito.Util.DefaultERTSResolver.do_resolve/1:

        # 1
        %Burrito.Builder.Target{debug?: false, erts_source: {:local_unpacked, [path: "/nix/store/hcl90mwii5l0mrsnrwlywh1da450ixqq-erlang-26.0.2/lib/erlang"]}, qualifiers: [libc: :gnu], cross_build: false, os: :linux, cpu: :x86_64, alias: :linux_amd64}

    Attempted function clauses (showing 4 out of 4):

        def do_resolve(%Burrito.Builder.Target{erts_source: {:runtime, _}} = target)
        def do_resolve(%Burrito.Builder.Target{erts_source: {:precompiled, version: otp_version}} = target) when is_binary(otp_version)
        def do_resolve(%Burrito.Builder.Target{erts_source: {:local, path: location}} = target)
        def do_resolve(%Burrito.Builder.Target{erts_source: {:url, url: location}} = target)

    (burrito 0.8.0) lib/util/default_erts_resolver.ex:14: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 0.8.0) lib/steps/fetch/resolve_erts.ex:34: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.4) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.4) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
```

mix.exs
```elixir
  # ... truncated

  def releases do
    [
      next_ls: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          targets: inject_custom_erts([
            darwin_arm64: [os: :darwin, cpu: :aarch64],
            darwin_amd64: [os: :darwin, cpu: :x86_64],
            linux_arm64: [os: :linux, cpu: :aarch64, libc: :gnu],
            linux_amd64: [os: :linux, cpu: :x86_64, libc: :gnu],
            linux_arm64_musl: [os: :linux, cpu: :aarch64, libc: :musl],
            linux_amd64_musl: [os: :linux, cpu: :x86_64, libc: :musl],
            windows_amd64: [os: :windows, cpu: :x86_64]
          ])
        ]
      ]
    ]
  end
  
  # ... truncated
  
  defp inject_custom_erts(targets) do
    # By default, Burrito downloads ERTS from https://burrito-otp.b-cdn.net.
    # When building with Nix, side-effects like network access are not allowed,
    # so we need to inject our own ERTS path.

    erts_path = System.get_env("BURRITO_ERTS_PATH", "")

    Enum.map(targets, fn {target_name, target_conf} ->
      case erts_path do
        "" -> {target_name, target_conf}
        path -> {target_name, [{:custom_erts, path} | target_conf]}
      end
    end)
  end
```

**Comment by mhanberg** [comment]
@doawoo elixir-tools related ☝️

**Comment by doawoo** [comment]
Seems like this could be a quick fix, lemme take a stab at it after lunch!

**Comment by jozuas** [comment]
Upon a closer look, I have noticed that it's not a typo, but rather a missing function head. I have updated the ticket title and description.

**Comment by jozuas** [comment]
The following fixes the problem

```elixir
  def do_resolve(%Target{erts_source: {:url, url: location}} = target) do
    url_string = URI.to_string(location)
    archive_data = get_erts(url_string)
    unpacked_location = do_unpack(archive_data, target)

    %Target{target | erts_source: {:local_unpacked, path: unpacked_location}}
  end

  # Fix code
  def do_resolve(%Target{erts_source: {:local_unpacked, path: _location}} = target) do
    target
  end
  # Fix code ends

  defp get_erts(tar_url) do
```

**Comment by doawoo** [comment]
thanks! pushed to `main`
