### ISSUE TITLE
macOS Sonoma fails to wrap

### ISSUE THREAD

**Issue by mhanberg** [burrito-elixir/burrito#106]
Related to https://github.com/elixir-tools/next-ls/issues/249

```
* assembling next_ls-0.12.7 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
> We couldn't find 7z in your PATH, 7z is required to build Windows releases. They will fail if you don't fix this!
> Target is being overridden with BURRITO_TARGET darwin_arm64
> Burrito is building target: darwin_arm64
> Burrito will build for target:
        OS: darwin
        CPU: aarch64
        Qualifiers: [libc: nil]
        Debug: false
----> PHASE: :fetch
--> Working directory: /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD
--> Resolving ERTS: {:precompiled, [version: "26.0.2"]}
--> Remote ERTS From Beam Machine: https://burrito-otp.b-cdn.net/OTP-26.0.2/darwin/aarch64/otp_26.0.2_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Found matching cached ERTS, using that
--> Unpacked ERTS to: /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/unpacked_erts_6A68B2DE23AD279E
----> PHASE: :patch
--> Replacing ERTS binaries...
--> Overwriting NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/asn1-5.1/priv/lib/asn1rt_nif.so with /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/unpacked_erts_6A68B2DE23AD279E/otp_26.0.2_darwin_aarch64_ssl_1.1.1s/lib/asn1-5.1/priv/lib/asn1rt_nif.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/asn1-5.1/priv/lib/asn1rt_nif.so
--> Overwriting NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/crypto-5.2/priv/lib/crypto.so with /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/unpacked_erts_6A68B2DE23AD279E/otp_26.0.2_darwin_aarch64_ssl_1.1.1s/lib/crypto-5.2/priv/lib/crypto.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/crypto-5.2/priv/lib/crypto.so
--> Overwriting NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/crypto-5.2/priv/lib/otp_test_engine.so with /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/unpacked_erts_6A68B2DE23AD279E/otp_26.0.2_darwin_aarch64_ssl_1.1.1s/lib/crypto-5.2/priv/lib/otp_test_engine.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/crypto-5.2/priv/lib/otp_test_engine.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/megaco-4.4.4/priv/lib/megaco_flex_scanner_drv.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/megaco-4.4.4/priv/lib/megaco_flex_scanner_drv_mt.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/runtime_tools-2.0/priv/lib/dyntrace.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/runtime_tools-2.0/priv/lib/trace_file_drv.so
--> Installed NIF library /var/folders/pb/rt73f0494wg4hkgl4dhzkk300000gn/T/tmp.bOmzdRGM93/burrito_build_1E2EBC712432C0DD/lib/runtime_tools-2.0/priv/lib/trace_ip_drv.so
----> PHASE: :build
--> Generating wrapper metadata file...
MachO Flush... error(link): undefined reference to symbol 'dyld_stub_binder'
error: UndefinedSymbolReference
--> Cleaning up...
--> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.5) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.5) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.5) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.5) lib/mix/cli.ex:92: Mix.CLI.run_task/2
```

**Comment by doawoo** [comment]
Ahh yes I've experienced this. This unfortunately requires us to bump Zig to a much newer version, which requires us to rewrite the `build.zig` file since that API has changed quite a bit. 

Assigning this to myself and I'll chip away at it!

**Comment by mhanberg** [comment]
Thanks!!

This shouldn't impact my GitHub releases as I'll keep that in macOS 13. But it'll impact users compiling from source.

**Comment by doawoo** [comment]
Thanks for testing! I'll merge!

**Comment by gangstead** [comment]
For anyone else getting this issue after updating to Sonoma make sure to `mix deps.unlock burrito` after updating your zig version so that you get the latest commit from this repo.
