### ISSUE TITLE
Fails to log error when failing to recompile NIF

### ISSUE THREAD

**Issue by mhanberg** [burrito-elixir/burrito#108]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: macOS 14
**Host CPU**: M1

Please run `zig version` in your Burrito project directory and write the version here:

0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.5 (compiled with Erlang/OTP 26)
```

------

### Target

**Host OS**: macOS
**Host CPU**: Intel

------

```
┌─ 09:32:03 PM
│next_ls on  main +1 -1 [$!⇕] via  v1.15.5 (OTP 26) took 1m2s
└─  nix build .#ci
warning: Git tree '/Users/mitchell/src/next_ls' is dirty
error: builder for '/nix/store/qj26nsdjlwjij4bmss48j6ira6x37800-next-ls-0.13.1.drv' failed with exit code 1;
       last 10 log lines:
       > --> Failed to rebuild exqlite for x86_64-macos!
       > ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: %IO.Stream{device: :standard_io, raw: false, line_or_bytes: :line}
       >     (burrito 0.8.0) lib/builder/log.ex:15: Burrito.Builder.Log.error/2
       >     (burrito 0.8.0) lib/steps/patch/recompile_nifs.ex:110: Burrito.Steps.Patch.RecompileNIFs.maybe_recompile_nif/4
       >     (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
       >     (burrito 0.8.0) lib/steps/patch/recompile_nifs.ex:17: Burrito.Steps.Patch.RecompileNIFs.execute/1
       >     (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
       >     (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       >     (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
       >     (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
       For full logs, run 'nix log /nix/store/qj26nsdjlwjij4bmss48j6ira6x37800-next-ls-0.13.1.drv'.
```

So the error is about trying to use an IO.Stream struct as a string. I'm not entirely sure what the error behind this is.

This only happened when building my Nix flake, not when building normally.

**Comment by doawoo** [comment]
Oh this looks fun, I'll get some nix going and see what's up

**Comment by doawoo** [comment]
Bump -- does this still happen with the Hex 1.0 release?

**Comment by mhanberg** [comment]
not sure, feel free to close and i'll come back if i see it again
