### ISSUE TITLE
Build failing on x86_64

### ISSUE THREAD

**Issue by jozuas** [burrito-elixir/burrito#109]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: NixOS
**Host CPU**:  x86_64

Please run `zig version` in your Burrito project directory and write the version here:
0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:
```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.5 (compiled with Erlang/OTP 26)
```

------

### Target

**Host OS**: NixOS
**Host CPU**: x86_64

------

```
juozas@nixos> nix build ./next-ls/
error: builder for '/nix/store/r4szvjz0wywkapailxws6bq0nrw0wvk8-next-ls-0.13.4.drv' failed with exit code 1;
       last 10 log lines:
       > --> Burrito failed to wrap up your app! Check the logs for more information.
       > ** (RuntimeError) Wrapper build failed
       >     (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
       >     (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
       >     (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       >     (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
       >     (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
       >     (mix 1.15.6) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
       >     (mix 1.15.6) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
       >     (mix 1.15.6) lib/mix/cli.ex:92: Mix.CLI.run_task/2
       For full logs, run 'nix log /nix/store/r4szvjz0wywkapailxws6bq0nrw0wvk8-next-ls-0.13.4.drv'.
```

Inside the log:
```
> Burrito is building target: linux_amd64
> Burrito will build for target:
        OS: linux
        CPU: x86_64
        Qualifiers: [libc: :gnu]
        Debug: false
----> PHASE: :fetch
--> Working directory: /build/burrito_build_C055F5B03D688FBC
--> Resolving ERTS: {:local_unpacked, [path: "/nix/store/399w5a3wpqfv92yk5cvrwil95pf7kpvk-erlang-26.0.2/lib/erlang"]}
----> PHASE: :patch
--> Replacing ERTS binaries...
----> PHASE: :build
--> Generating wrapper metadata file...
LLVM Emit Object... Semantic Analysis [2170] gfx1030... Semantic Analysis [2539] c3_2... Semantic Analysis [2718] addOneAssumeCapacity... Semantic Analysis [2811] isNativeCpu... Semantic Analysis [2922] deallocate... LLVM Emit Object... LLVM Emit Object... Semantic Analysis [2953] /build/deps/burrito/src/archiver.zig:213:97: error: expected 2  arguments, found 1
            const file = try fs.createFileAbsolute(full_file_path, .{ .truncate = true, .mode = @intCast(file_mode) });
                                                                                                ^~~~~~~~~~~~~~~~~~~
```

**Comment by jozuas** [comment]
@mhanberg

**Comment by mhanberg** [comment]
Probably related to bumping zig to 0.11.

**Comment by doawoo** [comment]
the error about `@intCast` requiring 2 args vs 1 usually points to outdated Zig... since that changed between 0.10.0 and 0.11.0

**Comment by mhanberg** [comment]
Oh yes @jozuas, this is probably because the patch you're working on, you reverted zig back to 0.10. I left a comment in that in the PR

**Comment by jozuas** [comment]
Ah, goddamnit. Sorry, didn't see the typo ...
