### ISSUE TITLE
Unable to download a "pre-compiled Erlang"

### ISSUE THREAD

**Issue by sachamasry** [burrito-elixir/burrito#133]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: MacOS Ventura 13.6.3
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here: 0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here: Elixir 1.16.1 (compiled with Erlang/OTP 26), Erlang 26.2.2 (Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [dtrace])

------

### Target

**Host OS**: Same as host
**Host CPU**: x86_64
**Host LibC and Version** (eg. gnu/musl x.y.z ...)

------

Can't fetch pre-built ERTS binary:

```
> Burrito will build for target:
        OS: darwin
        CPU: x86_64
        Qualifiers: [libc: nil]
        Debug: false
----> PHASE: :fetch
--> Working directory: /var/folders/x1/h96gsd653jncyth4y8hznhqc0000gn/T/burrito_build_EF1D4ED46CBD5FC4
--> Resolving ERTS: {:precompiled, [version: "26.2.2"]}
--> Remote ERTS From Beam Machine: https://burrito-otp.b-cdn.net/OTP-26.2.2/darwin/x86_64/otp_26.2.2_darwin_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://burrito-otp.b-cdn.net/OTP-26.2.2/darwin/x86_64/otp_26.2.2_darwin_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://burrito-otp.b-cdn.net/OTP-26.2.2/darwin/x86_64/otp_26.2.2_darwin_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:91: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 0.8.0) lib/steps/fetch/resolve_erts.ex:34: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.1) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.16.1) lib/mix/tasks/release.ex:1076: Mix.Tasks.Release.run_steps/1
```

**Comment by doawoo** [comment]
Hi there, I see the CDN URL that's being used is the old non-universal CDN. This tells me your Burrito is out of date and still using the old git release. 

You can update to the latest hex.pm release here: https://hex.pm/packages/burrito

Thanks!

**Comment by sachamasry** [comment]
You are right @doawoo I was using a library, itself running on an older version of Burrito. Thank you!
