### ISSUE TITLE
Unable to build on github action

### ISSUE THREAD

**Issue by sleipnir** [burrito-elixir/burrito#150]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: ubuntu-latest
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here: 0.13.0

Please run `elixir -v` in your Burrito project directory and write the version here: 

------

### Target

**Host OS**: Linux
**Host CPU**: x86_64, aarch64 

------

When I runn a github action I found:
```
Generated spawnctl app
* assembling spawnctl-0.0.0-local.dev on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
* creating _build/prod/rel/spawnctl/releases/0.0.0-local.dev/vm.args
* creating _build/prod/rel/spawnctl/releases/0.0.0-local.dev/remote.vm.args
* creating _build/prod/rel/spawnctl/releases/0.0.0-local.dev/env.sh
* creating _build/prod/rel/spawnctl/releases/0.0.0-local.dev/env.bat
> Burrito is building target: linux
> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: []
	Debug: false
----> PHASE: :fetch
Custom build step!
Current Target: %Burrito.Builder.Target{debug?: false, erts_source: {:precompiled, [version: "25.3.2.13"]}, qualifiers: [], cross_build: true, os: :linux, cpu: :x86_64, alias: :linux}
--> Working directory: /tmp/burrito_build_2CA5B7FB6BD6F870
--> Fetching musl libc runtime binary for Linux...
--> Downloading file: https://beam-machine-universal.b-cdn.net/musl/libc-musl-17613ec13d9aa9e5e907e6750785c5bbed3ad49472ec12281f592e2f0f2d3dbd.so?please-respect-my-bandwidth-costs=thank-you
00:37:24.893 [info] Wrote new cache file: /home/runner/.cache/burrito_file_cache/435E138697EB2C0A5F113D277FEEC65E5E524E41
--> Wrote musl runtime file: /home/runner/work/spawn/spawn/spawnctl/deps/burrito/src/musl-runtime.so
--> Resolving ERTS: {:precompiled, [version: "25.3.2.13"]}
--> Remote ERTS From Beam Machine: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.13/linux/x86_64/any/otp_25.3.2.13_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.13/linux/x86_64/any/otp_25.3.2.13_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://beam-machine-universal.b-cdn.net/OTP-25.3.2.13/linux/x86_64/any/otp_25.3.2.13_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 1.1.0) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 1.1.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 1.1.0) lib/steps/fetch/resolve_erts.ex:30: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 1.1.0) lib/builder/builder.ex:140: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.8) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.8) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 1.1.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.8) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
make: *** [Makefile:41: build-cli] Error 1
```

But the same code and configuration in my local ubuntu works as expect.

**Comment by doawoo** [comment]
Whoops! We didn't have that latest hot fix release of OTP on our CDN. 
I just finished kicking off the uploading the builds, you should be able to re-run your build and it should work!

**Comment by sleipnir** [comment]
Cool @doawoo thanks for the quick response. I will test it!

**Comment by sleipnir** [comment]
Works. Thank you @doawoo

**Comment by sleipnir** [comment]
Hi @doawoo I experiment the same issue again. 

```elixir
 --> Resolving ERTS: {:precompiled, [version: "25.3.2.14"]}
--> Remote ERTS From Beam Machine: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.14/linux/x86_64/any/otp_25.3.2.14_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.14/linux/x86_64/any/otp_25.3.2.14_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://beam-machine-universal.b-cdn.net/OTP-25.3.2.14/linux/x86_64/any/otp_25.3.2.14_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 1.1.0) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 1.1.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 1.1.0) lib/steps/fetch/resolve_erts.ex:30: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 1.1.0) lib/builder/builder.ex:140: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.8) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.8) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 1.1.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.8) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
```

**Comment by doawoo** [comment]
Looks like another release went out for that branch of OTP. I just built, and uploaded it. Try running your action again!

**Comment by sleipnir** [comment]
> Looks like another release went out for that branch of OTP. I just built, and uploaded it. Try running your action again!

Thank you. Works fine now!
