### ISSUE TITLE
Precompiled Erlang VM not found

### ISSUE THREAD

**Issue by tduccuong** [burrito-elixir/burrito#164]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: Manjaro Linux 24.1.2
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here: `0.13.0`

Please run `elixir -v` in your Burrito project directory and write the version here: `1.14.2`

------

### Target

**Host OS**: Manjaro Linux 24.1.2
**Host CPU**: x86_64
**Host LibC and Version**: GNU libc 2.40

------

I issued the command for Linux alias and got this error:

```
> Target is being overridden with BURRITO_TARGET linux
> Burrito is building target: linux
> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: []
	Debug: false
----> PHASE: :fetch
--> Working directory: /tmp/burrito_build_9FB14B8F8DE4F7FC
--> Fetching musl libc runtime binary for Linux...
--> Found matching cached musl runtime, using that
--> Wrote musl runtime file: /path/to/myproject/deps/burrito/src/musl-runtime.so
--> Resolving ERTS: {:precompiled, [version: "25.1.2"]}
--> Remote ERTS From Beam Machine: https://beam-machine-universal.b-cdn.net/OTP-25.1.2/linux/x86_64/any/otp_25.1.2_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://beam-machine-universal.b-cdn.net/OTP-25.1.2/linux/x86_64/any/otp_25.1.2_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://beam-machine-universal.b-cdn.net/OTP-25.1.2/linux/x86_64/any/otp_25.1.2_linux_any_x86_64_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 1.2.0) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 1.2.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 1.2.0) lib/steps/fetch/resolve_erts.ex:30: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 1.2.0) lib/builder/builder.ex:140: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 1.2.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.14.2) lib/mix/tasks/release.ex:1068: Mix.Tasks.Release.run_steps/1
```

The error told me to open an issue here for help!

Thanks a lot!

**Comment by doawoo** [comment]
Built and uploaded! Thanks for the report!

**Comment by tduccuong** [comment]
It works now, thanks a lot! :+1:
