### ISSUE TITLE
Burrito fails to build.

### ISSUE THREAD

**Issue by kpanic** [burrito-elixir/burrito#74]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: linux
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here:

`0.9.1`

Please run `elixir -v` in your Burrito project directory and write the version here:
```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```
------

### Target

**Host OS**: linux
**Host CPU**: x86_64
**Host LibC and Version** glibc 2.36-6 

------
```elixir
$ BURRITO_TARGET=linux MIX_ENV=prod mix release
Generated gigex app
* assembling gigex-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
-> Burrito is building target: linux
-> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: [libc: :glibc]
	Debug: false
--> PHASE: :fetch
---> Working directory: /tmp/burrito_build_228018F47118BC7F
---> Resolving ERTS: {:runtime, []}
--> PHASE: :patch
--> PHASE: :build
---> Generating wrapper metadata file...
./build.zig:74:20: error: no member named 'addIncludePath' in struct 'std.build.LibExeObjStep'
        wrapper_exe.addIncludePath("src/");
                   ^
./src/archiver.zig:54:62: error: no member named 'mode' in struct 'std.fs.file.OpenFlags'
    const arch_file = try fs.cwd().openFile(archive_path, .{ .mode = .read_write });
                                                             ^
---> Cleaning up...
---> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:59: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:146: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:95: Burrito.Builder.build/1
    (mix 1.14.2) lib/mix/tasks/release.ex:1068: Mix.Tasks.Release.run_steps/1
    (mix 1.14.2) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Maybe it's the zig version that I have to upgrade? thanks!**

**Comment by kpanic** [comment]
With:

```bash
$ zig version
0.10.0
```

it has built.

```elixir
$ BURRITO_TARGET=linux MIX_ENV=prod mix release
Release gigex-0.1.0 already exists. Overwrite? [Yn] 
* assembling gigex-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
-> Target is being overridden with BURRITO_TARGET linux
-> Burrito is building target: linux
-> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: [libc: :glibc]
	Debug: false
--> PHASE: :fetch
---> Working directory: /tmp/burrito_build_84B2B78F4700139A
---> Resolving ERTS: {:runtime, []}
--> PHASE: :patch
--> PHASE: :build
---> Generating wrapper metadata file...
info: Zig is building an Elixir binary... ⚡
info: Generating and compressing release payload... 📦
info: 🔍 Files Packed: 1286
info: Archived 1286 files into payload! 📥
info: Building wrapper and embedding payload... 🌯
info: DONE 🚀
---> Cleaning up...



🌯 Burrito has wrapped your Elixir app! 🌯
	Output Path: /home/kpanic/src/gigex/burrito_out/gigex_linux



Release created at _build/prod/rel/gigex

    # To start your system
    _build/prod/rel/gigex/bin/gigex start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/gigex/bin/gigex remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/gigex/bin/gigex stop

To list all commands:

    _build/prod/rel/gigex/bin/gigex
```
I'll open a PR to update the README that can be discarded if not necessary

**Comment by doawoo** [comment]
Thanks for the README update, that's indeed the cause, we use `0.10.0` now :)
